#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string
    description: L'identifiant du produit
  name:
    type: string
    description: Le nom du produit
  prix:
    type: integer
    description: Le prix du produit
  stock:
    type: integer
    description: Le stock du produit
